# Generated by Django 5.2 on 2025-07-10 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ranking_user_alter_comparison_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ranking',
            name='unique_product_ranking',
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'product'), name='unique_product_ranking_for_user'),
        ),
    ]
