FROM node:20.14-slim as build

WORKDIR /app

COPY . .

COPY .env.example .env

RUN npm install

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80