services:
    frontend:
        build:
            context: frontend
        env_file:
            - frontend/.env
        ports:
            - 4173:4173
        volumes:
            - ./frontend:/app

    backend:
        build:
            context: backend
        env_file:
            - backend/.env
        environment:
            - DB_HOST=db
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
            - static_volume:/app/static
        depends_on:
            - db
        
    db:
        image: postgres:17-alpine
        restart: always
        env_file:
            - backend/.env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    static_volume:
    postgres_data: